### ISSUE TITLE
Week 06 - Day 3 - Choose your own API Adventure

### ISSUE THREAD

**Issue by mdewey** [Ahseeah/assignments#21]
# Choose your own API Adventure

In this assignment, you'll build a front end for an API of your choice

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some are great, and some are terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

_NOTE_ You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

_NOTE_ You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [ ] Read your API docs
- [ ] Use Postman to make some API requests to be familiar with the API and the data it returns
- [ ] Create a list of the features you are going to create and how they will work
- [ ] Design your User Interface
- [ ] create-react-app
- [ ] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

**Comment by Ahseeah** [comment]
https://github.com/Ahseeah/amiibo-app

**Comment by mdewey** [comment]
Looks like you are missing the latest commit in your code. If you need help committing and pushing let me know

**Comment by Ahseeah** [comment]
Whoops! Re-submitting now

**Comment by Ahseeah** [comment]
https://github.com/Ahseeah/amiibo-app

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
